dist: trusty
sudo: false

language: node_js

node_js:
  - 7

script:
  - npm run eslint
  - npm run cspell

deploy:
  provider: npm
  api_key: $NPM_AUTH_TOKEN
  email: $NPM_EMAIL
  on:
    tags: true
